name: Check IP Status

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-ip-status:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the script to check IP status
      - name: Run IP status check script
        run: node checkIP.js
      - name: Upload results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: hasil-cek
          path: hasil_cek.csv

